[package]
name = "valeriyya"
version = "0.1.2"
edition = "2021"

[dependencies]
tokio = { version = "1.13.0", features = ["rt-multi-thread"] }
serenity = { version = "0.10.0", default-features = false, features = ["builder", "cache", "client", "gateway", "http", "model", "utils", "rustls_backend"] }
discord-rpc-client = "^0.3"

