[package]
name = "valeriyya"
version = "0.1.1"
edition = "2021"

[dependencies]
tokio = { version = "1.17.0", features = ["rt-multi-thread"] }
chrono = "0.4.19"
serde = "1.0.137"
regex = "1.5.6"
bson = "2.3.0"
once_cell = "1.7"
reqwest = "0.11.11"
ytextract = "0.11.0"

[dependencies.serenity]
version = "0.11.2"
default-features = false
features = ["builder", "cache", "client", "gateway", "http", "model", "utils", "rustls_backend", "chrono", "voice"]

[dependencies.poise]
version = "0.2.2"

[dependencies.mongodb]
version = "2.2.2"
default-features = false
features = ["async-std-runtime"]

[dependencies.songbird]
git = "https://github.com/FelixMcFelix/songbird"
features = ["builtin-queue"]
branch = "symphonia"

[dependencies.symphonia]
version = "0.5"
features = ["aac", "mp3", "isomp4", "alac"]

[patch."https://github.com/serenity-rs/serenity"]
serenity = { version = "0.11.2" }
