[package]
name = "valeriyya"
version = "0.1.1"
edition = "2021"

[dependencies]
tokio = { version = "1.17.0", features = ["rt-multi-thread"] }
chrono = "0.4.19"
serde = "1.0.136"
regex = "1.5.5"
dotenv = "0.15.0"
bson = "2.2.0"
once_cell = "1.7"

[dependencies.serenity]
version = "0.11.1"
default-features = false
features = ["builder", "cache", "client", "gateway", "http", "model", "utils", "rustls_backend", "chrono", "voice"]

[dependencies.poise]
version = "0.1.0"

[dependencies.mongodb]
version = "2.2.0"
default-features = false
features = ["async-std-runtime"]

[dependencies.songbird]
git = "https://github.com/serenity-rs/songbird"
features = ["builtin-queue"]
branch = "next"

[patch."https://github.com/serenity-rs/serenity"]
serenity = { version = "0.11.1" }
