[package]
name = "valeriyya"
version = "0.1.1"
edition = "2021"

[dependencies]
tokio = { version = "1.17.0", features = ["rt-multi-thread"] }
chrono = "0.4.19"
serde = "1.0.136"
regex = "1.5.5"
dotenv = "0.15.0"
bson = "2.2.0"
quote = "1.0.18"

[dependencies.serenity]
git = "https://github.com/serenity-rs/serenity"
branch = "next"
default-features = false
features = ["builder", "cache", "client", "gateway", "http", "model", "utils", "rustls_backend", "unstable_discord_api"]

[dependencies.poise]
git = "https://github.com/kangalioo/poise"
branch = "master"

[dependencies.mongodb]
version = "2.2.0"
default-features = false
features = ["async-std-runtime"]